<a href="https://colab.research.google.com/github/cadanganfotoaditt1-cpu/haha/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as a



1. Array yang berisi 10 angka
[[1 2 3]
 [3 4 5]]

2. Array berisi nilai mahasiswa dan tampilkan nilai tertinggi:  
[85 90 78 92 88 95 80 91 89 94 87 93 86 90 91]
Nilai tertinggi: 95


In [18]:
print("\n2. Array berisi nilai mahasiswa dan tampilkan nilai tertinggi:  ")
nilai_mahasiswa = a.array([85, 90, 78, 92, 88, 95, 80, 91, 89, 94, 87, 93, 86, 90, 91])
nilai_tertinggi = a.max(nilai_mahasiswa)
nilai_rata = a.average(nilai_mahasiswa)
nilai_terkecil = a.min(nilai_mahasiswa)

print(nilai_mahasiswa)
print("\nNilai tertinggi:", nilai_tertinggi)
print("\nNilai Rata:", nilai_rata)
print("\nNilai Terendah:", nilai_terkecil)


2. Array berisi nilai mahasiswa dan tampilkan nilai tertinggi:  


In [22]:


matrix = a.array([[1, 2, 3], [3, 4, 5]])


print(matrix[1,1])
print("\n")
print(a.sum(matrix))



matriks = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
print(matriks)
print(matriks[1,1])


4


18
